import ROOT

# Disable pop-up windows for smoother running over ssh
ROOT.gROOT.SetBatch(True)

f_corr = ROOT.TFile("$CMSSW_BASE/src/Analysis/JMEDAS/notebooks/files/ttjets_corr.root")

h_ptAK4_corr = f_corr.Get("h_ptAK4")
h_ptAK4Gen_corr = f_corr.Get("h_ptAK4Gen")

h_ptAK4Gen_corr.SetLineStyle(2) 
h_ptAK4Gen_corr.SetLineColor(2) 
c_corr = ROOT.TCanvas('c_corr', 'c', 800, 400)
c_corr.Divide(2,1)
c_corr.cd(1)
ROOT.gPad.SetLogy()
h_ptAK4_corr.Draw()
h_ptAK4_corr.SetTitle("AK4 Jet p_{T} (corrected)")
h_ptAK4Gen_corr.Draw("same")
h_ptAK4_corr.GetXaxis().SetRangeUser(0, 1000)
leg_corr = ROOT.TLegend(0.6, 0.6, 0.8, 0.8)
leg_corr.AddEntry(h_ptAK4, "RECO", "l")
leg_corr.AddEntry(h_ptAK4Gen, "GEN", "l")
leg_corr.SetFillColor(0)
leg_corr.SetLineColor(0)
leg_corr.Draw("same")

c_corr.cd(2)
ROOT.gPad.SetLogy()
h_ptAK4.Draw()
h_ptAK4.SetTitle("AK4 Jet p_{T} (uncorrected)")
h_ptAK4Gen.Draw("same")
h_ptAK4.GetXaxis().SetRangeUser(0, 1000)
leg = ROOT.TLegend(0.6, 0.6, 0.8, 0.8)
leg.AddEntry(h_ptAK4, "RECO", "l")
leg.AddEntry(h_ptAK4Gen, "GEN", "l")
leg.SetFillColor(0)
leg.SetLineColor(0)
leg.Draw("same")

c_corr.Draw()
c_corr.Print('JEC_part2a.pdf','pdf')

c_compare = ROOT.TCanvas("c_compare", "c_compare", 400, 400)
c_compare.SetLogy()
h_ptAK4_norm = h_ptAK4.Clone()
h_ptAK4_norm.Scale(1. / h_ptAK4_norm.Integral())
h_ptAK4_norm.SetLineStyle(2)
h_ptAK4_norm.SetLineColor(ROOT.kRed)
h_ptAK4_norm.SetTitle("Corrected vs. Uncorrected")
h_ptAK4_norm.Draw("hist")

h_ptAK4_corr_norm = h_ptAK4_corr.Clone()
h_ptAK4_corr_norm.Scale(1. / h_ptAK4_corr_norm.Integral())
h_ptAK4_corr_norm.SetLineStyle(1)
h_ptAK4_corr_norm.SetLineColor(ROOT.kBlack)
h_ptAK4_corr_norm.Draw("hist same")
l_compare = ROOT.TLegend(0.55, 0.5, 0.88, 0.8)
l_compare.SetFillColor(0)
l_compare.SetBorderSize(0)
l_compare.AddEntry(h_ptAK4_norm, "Uncorrected AK4PFJets", "l")
l_compare.AddEntry(h_ptAK4_corr_norm, "Corrected AK4PFJets", "l")
l_compare.Draw()
c_compare.Draw()
c_compare.Print('JEC_part2b','pdf')
